# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='valide',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='mdp',
            field=models.CharField(max_length=50, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='anneUniver',
            field=models.CharField(max_length=12, verbose_name='Ann\xe9e universitaire'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='nb_inscrit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='mdp',
            field=models.CharField(max_length=50, verbose_name='Mot de passe'),
        ),
    ]
